<?php

namespace Insat\Gl2Bundle\Repository;

/**
 * TypeClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeClubRepository extends \Doctrine\ORM\EntityRepository
{
}
