todo_list:
    path:     /list
    defaults: { _controller: InsatGl2Bundle:Default:index }

new_todo:
    path:     /cc/add/{cle}/{valeur}
    defaults: { _controller: InsatGl2Bundle:Default:addTodo }

insat_gl2_test:
    path:     /cc/{param}
    defaults: { _controller: InsatGl2Bundle:Default:test }
index:
    path:     /todo
    defaults: { _controller: InsatGl2Bundle:Todo:index }

add_todo:
    path:     /todo/add/{cle}/{valeur}
    defaults: { _controller: InsatGl2Bundle:Todo:addTodo }

accueil:
    path:     /accueil
    defaults: { _controller: InsatGl2Bundle:Todo:accueil }


testh:
    path:     /testh
    defaults: { _controller: InsatGl2Bundle:Todo:testh }

add:
    path:     /add
    defaults: { _controller: InsatGl2Bundle:Personne:add }

show_personnes:
    path:     /show
    defaults: { _controller: InsatGl2Bundle:Personne:show }

update_personnes:
    path:     /update/{id}
    defaults: { _controller: InsatGl2Bundle:Personne:updatePersonne }
show_form:
    path:     /showForm/{id}
    defaults: { _controller: InsatGl2Bundle:Club:showForm }

list_clubs:
    path:     /listClubs
    defaults: { _controller: InsatGl2Bundle:Club:listClubs }
